sudo: required
services:
  - docker
before_install:
        - docker build -t sswaminath/docker-multi-react -f ./client/Dockerfile.dev ./client

# Script is the section where we run all tests - 08292019
script:
  - docker run -e CI=true -t sswaminath/docker-multi-react npm test -- --coverage

after_success:
  - docker build -t sswaminath/docker-multi-client ./client
  - docker build -t sswaminath/docker-multi-nginx ./nginx
  - docker build -t sswaminath/docker-multi-server ./server
  - docker build -t sswaminath/docker-multi-worker ./worker

  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  - docker push sswaminath/docker-multi-client
  - docker push sswaminath/docker-multi-nginx
  - docker push sswaminath/docker-multi-server
  - docker push sswaminath/docker-multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: khoma 
  env: khoma-env
  bucket_name: elasticbeanstalk-us-east-1-138402561056
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


